### ISSUE TITLE
Is there any way to know/set max memory usage and timelimit?

### ISSUE THREAD

**Issue by flaviolc18** [diffblue/2ls#142]
I'm trying to run the tool for a benchmark experiment but i didn't find anywhere in the README neither in the help message about these options. There's a --show-stats option but it doesn't show what i'm looking for.

**Comment by viktormalik** [comment]
As far as I know, there is no way to set this. For experiments where a resource limit is needed, we use [BenchExec](https://github.com/sosy-lab/benchexec/) that is used in [SV-COMP](https://sv-comp.sosy-lab.org/2020/). You could do a similar thing to what BenchExec does yourself - run 2LS in a Linux container to set memory usage limit and use the `timeout` command to specify the time limit.

This is as much as I know, perhaps @peterschrammel could be able to help you better.

**Comment by peterschrammel** [comment]
Yes, this would be my recommendation too. There are also tools like https://www.cril.univ-artois.fr/~roussel/runsolver/ that package that functionality.

**Comment by flaviolc18** [comment]
Ok, thank you for the information!
