### ISSUE TITLE
decision guiding the search 

### ISSUE THREAD

**Issue by rajdeep87** [diffblue/2ls#15]
Consider the program below:
!(x#22 == y#23 || !$guard#20)
TRUE
$guard#0 == TRUE
$guard#20 == ($cond#19 && $guard#0)
x#22 == 1u + x#20
y#23 == 1u + y#21
$cond#19 == (x#16 == y#18)
x#20 == 1u + x#16
y#21 == 1u + y#18

ACDL performed the following run:
DL0: propagate(AI) --> UNKNOWN
DL1: decide
Propagate(AI) --> UNKNOWN
DL2: decide
Propagate(AI) --> UNKNOWN
DL3: decide
Propagate(AI) --> BOTTOM
Learn: (!DL1 || !DL2 || !DL3), where DL3 is the last uip
Backtrack to DL2
Learned clause is UNIT, Propagation(PROPOSITIONAL) --> !DL2
Propagate(AI)
BOTTOM
Learn: (!DL1)
Backtrack to DL0, because the learnt clause has only one literal at present decision level
Propagate(PROPOSITIONAL) --> both learned clauses are Satisfying, no new propagation
Propagate(AI)
UNKNOWN
DL4: decide
Propagate(PROPOSITIONAL)
Propagate(AI)
.............
DL39:decide ...

This now continues with other decisions.
The point here is that when we propagated after the second backtrack, it lead to UNKNOWN.
That deviated the search. If this propagation had lead to BOTTOM, we would have terminated with
SAFE because we were already in DL0 and no further propagation would have been possible.

I identified that the problem is due to bad decision. And ACDL could not recover from bad decision in this example. The decisions are as follows:
DL1: (x#20 <= 1u) 
DL2: (y#21 <= 1u) 
DL3: (y#18 <= 1u)
Clearly, DL1 and DL2 are decisions on variables which are overwritten in SSA whereas DL3 is the decision on input variable which does not appear in the lhs of any SSA. If DL3 was made as the first decision, then ACDL would have terminated right after first backtracking since it would have identified the conflict in DL1 and immediately backtracked to DL0 to prove the remaining case safe.

**Comment by peterschrammel** [comment]
Why don't you make decisions following all rows in the meet_irreducible_template? Including x-y etc with --octagons

**Comment by rajdeep87** [comment]
There are few aspects here:
0> Do we restrict the decision making on the variables -- x#16, y#18 only. In that case, a filtering logic would be able to filter out variables which should not be allowed to make decisions, just like we don't make decisions on guard variables or loopselect variable.
1> Decisions with intervals, just like,  (y#18 <= 1u), alone would have been sufficient to prove safety. 
2> Decisions with octagons is definitely possible. The implementation is under progress.

**Comment by peterschrammel** [comment]
0> For a complete decision heuristics, you eventually have to make decisions on any variable. Side remark:  constructing meet irreducibles is a domain task (e.g. as implemented in the split() function).
1> No. You would have to enumerate all 2^32 pairs of singleton intervals where x and y have the same value to prove that program using intervals
2> Mind that the decision heuristics should be domain-independent. We should only use domain-dependent heuristics as optimisation hacks, but that's out of scope at the moment.
