### ISSUE TITLE
Move to clang-format

### ISSUE THREAD

**Issue by viktormalik** [diffblue/2ls#165]
The existing code formatting scripts (`scripts/run_lint` and `scripts/cpplint.py`) seem not to work anymore (never reporting an error).

I'd suggest moving to clang-format, which is, IIUC, what CBMC uses. This will require some changes to the style, e.g. clang-format does not allow to omit spaces around operators. We wouldn't need to update the entire codebase at once, we can just run it on the changed lines in each PR (either by using CBMC's scripts for that or `git clang-format`).

@peterschrammel WDYT?

**Comment by peterschrammel** [comment]
Yes, that's a good idea.
