### ISSUE TITLE
gamma-completeness check too restrictive for guard variables in assertions

### ISSUE THREAD

**Issue by rajdeep87** [diffblue/2ls#17]
Consider a scenario where ACDL solver computed singletons for all variables (after several decisions and deductions). This means that there are no non-singletons left and hence no more decisions can be made. The gamma-completeness check can still fail for guard variables where it may find that the negation of a guard variable when conjuncted with the abstract value is not UNSAT (hence failed). But, this check is hurting us now. 
Consider a guard variable in the assert statement.
(A) !(z#38 == -2 || !$guard#27)
ACDL deduced singletons for all variables in the program (guard#27=true, z#38=1, ... ) 
The gamma-completeness check passes for all variables in this program except guard#27.
However, guard#27 must be true for checking this assertion. 
Does it make sense for gamma completeness check to fail for guard variable present in the assertion when we have already reached a concrete counterexample. Note also that the decision heuristics cannot make any further decisions since all variables are already singletons and there is no backtracking possible to make something non-singleton in this case.

**Comment by peterschrammel** [comment]
Decision heuristics and completeness check are separate components of the system that have to do their job independently regardless of the other.
Hence, the culprit here is not the completeness check, but your decision heuristics that is incomplete.

**Comment by rajdeep87** [comment]
I agree that they are independent component. 
But the completeness check fails for the guard ($guard#27) in the assertion.
(A) !(z#38 == -2 || !$guard#27)
Here, (guard#27 => (z#38==-2)), hence guard#27 being true means that the consequent of the assertion is actually checked. However, $guard#27=false means that the assertion is vacuously true.  
Also note that $guard#27 is always deduced irrespective of what decisions you make.

**Comment by peterschrammel** [comment]
I don't understand why the completeness check should fail then if guard#27 has been deduced true?

**Comment by rajdeep87** [comment]
The abstract value for completeness check is as follows:
[ACDL-DOMAIN] is_complete? $guard#27 && $cond#25 && $guard#0 && !(x#24 >= 0) && !(-((signed __CPROVER_bitvector[33])x#24) >= 2) && !(x#26 >= 3) && !(-((signed __CPROVER_bitvector[33])x#26) >= -1) && !(-((signed __CPROVER_bitvector[33])x#phi27) >= 2) && !(-((signed __CPROVER_bitvector[33])a#32) >= 2) && !(-((signed __CPROVER_bitvector[33])id#return_value#33) >= 2) && !(-((signed __CPROVER_bitvector[33])k#36) >= 2) && !$cond#23 && $guard#24 && !$guard#26 && !(x#phi27 >= 0) && !(a#32 >= 0) && !(z#38 >= 2) && !(id#return_value#33 >= 0) && !(k#36 >= 0) && !(-((signed __CPROVER_bitvector[33])z#38) >= 0)

The logic for checking completeness is to iterate over the abstract value, negate each element, and check if it is UNSAT when conjuncted with the abstract value. In doing so, the following check failed:

"check !($guard#27 == TRUE)  is not complete"

All the meet irreducibles in the abstract value are already singletons. As said before, the guard#27 is deduced TRUE and the above check ($guard#27 != TRUE) means that the assertion is vacuously true. So, the completeness check for guard#27 is irrelevant ?

**Comment by peterschrammel** [comment]
The formula the way it is constructed must be UNSAT for guard#27. Please investigate what is going wrong.
Irrelevance is not the point.

**Comment by rajdeep87** [comment]
Identified the problem. It is not due to guard#27. 
The is_complete routine iterates overall all program variables, but some variables may not be present in the abstract value (because no deductions were made involving these variables, hence not in trail and not in abstract value), so is_complete check fails for those variables that does not appear in the abstract value. 

If is_complete routine has to check completeness for all variables (symbols) in the program, then we need to guarantee that the domain returns deductions (meet irreducibles) involving all program variables.

**Comment by peterschrammel** [comment]
That means that there are variables that evade your decision heuristics...

**Comment by rajdeep87** [comment]
But in this example, there is some bug in deduction..The deduction did not return any new information about a particular variable (c#22) when the following statement is popped. 
Pop: $cond#23 == (c#22 == FALSE)
[ACDL-DOMAIN] projected(main::1::c#22): $guard#27 && $cond#25 && $guard#0 && !(x#24 >= 0) && !(-((signed __CPROVER_bitvector[33])x#24) >= 2) && !(x#26 >= 3) && !(-((signed __CPROVER_bitvector[33])x#26) >= -1) && !(x#phi27 >= 3) && !(-((signed __CPROVER_bitvector[33])x#phi27) >= 2) && !(a#32 >= 3) && !(-((signed __CPROVER_bitvector[33])a#32) >= 2)
[ACDL-DOMAIN] deductions(main::1::c#22):

Not sure why the deduction is empty here ? Shouldn't it return (c#22 == FALSE)

The decision heuristics actually did not skip this variable (c#22). It tried to make a decision on c#22,but it could not compute lower or upper value for this variable (needed for splitting) since c#22 did not appear in the abstract value. I will fix this issue. It should make decision regardless.

**Comment by peterschrammel** [comment]
1. It can only deduce if $cond#23 is determined.
2. Yes, it should make a decision regardless.

**Comment by rajdeep87** [comment]
1. yes, a decision on $cond#23 is made (decision= !$cond#23), but the domain still could not deduce that (c#22!=FALSE). I spotted the bug in the domain implementation. No deductions are made currently when the projected variable is a ID_bool and its literal is a constant (TRUE in this example). 
2. The decision heuristics is fixed now.

**Comment by rajdeep87** [comment]
Convert "_Bool" to 1-bit boolean.
