### ISSUE TITLE
Checking consistency of trail after adding a decision

### ISSUE THREAD

**Issue by rajdeep87** [diffblue/2ls#21]
A new decision added to the trail can lead to inconsistent trail (Abstract value is UNSAT). 
Consider the following decision in octagon domain:
NEW DECISION: 
(unsigned __CPROVER_bitvector[33])x#16 + (unsigned __CPROVER_bitvector[33])x#22 <= 1

Checking consistency of trail after adding decision:
----------------------------------------------------------------
$guard#20 && $guard#0 && $cond#19 && (signed __CPROVER_bitvector[33])x#16 - (signed __CPROVER_bitvector[33])y#23 <= 4294967294 && y#21 <= 1u && !(y#23 >= 3u) && !(-((signed __CPROVER_bitvector[33])y#23) >= 0) && !((unsigned __CPROVER_bitvector[33])x#22 + (unsigned __CPROVER_bitvector[33])y#18 <= 1) && (unsigned __CPROVER_bitvector[33])x#20 + (unsigned __CPROVER_bitvector[33])y#21 <= 1 && !(x#22 >= 3u) && !(-((signed __CPROVER_bitvector[33])x#22) >= 0) && !((unsigned __CPROVER_bitvector[33])x#20 + (unsigned __CPROVER_bitvector[33])x#22 <= 1) && !((unsigned __CPROVER_bitvector[33])x#20 + (unsigned __CPROVER_bitvector[33])y#21 <= 0) && !((unsigned __CPROVER_bitvector[33])x#22 + (unsigned __CPROVER_bitvector[33])y#21 <= 1) && !((unsigned __CPROVER_bitvector[33])y#18 + (unsigned __CPROVER_bitvector[33])y#21 <= 1) && !(-((signed __CPROVER_bitvector[33])x#16) >= 0) && **(unsigned __CPROVER_bitvector[33])x#16 + (unsigned __CPROVER_bitvector[33])x#22 <= 1**
                                       
The trail is inconsistent after addition of the last decision. This is because x#16>0 and x#22>0, so the last decision (x#16+x#22<=1) leads to UNSAT, thus making the trail inconsistent. 

Presently, the consistency check happens inside the acdl solver when a decision heuristics returns a decision. But should it be part of the decision heuristics to abandon such decisions when it leads to inconsistent trail ?

**Comment by rajdeep87** [comment]
This checking is now done inside each decision heuristics -- random, ordered, berkmin, octagon.
The idea is to return only those decisions to the acdl solver that does not make the trail inconsistent.

**Comment by peterschrammel** [comment]
This should be part of acdl_domaint::split. 
A decision heuristics must not make inconsistent decisions.
