### ISSUE TITLE
Deductions with Octagon domain

### ISSUE THREAD

**Issue by rajdeep87** [diffblue/2ls#23]
The deduction using Octagon domain can not return relevant meet irreducibles.
Consider a program below:
int main() {
 unsigned x, y;
 __CPROVER_assume(x==y);
 x++; y++;
 x++; y++;
 assert(x==y);
}

Using Interproc analyzer with forward analysis and octagon domain, the following annotated code 
is obtained :
Annotated program after forward analysis
var x : int, y : int;
begin
  assume x == y; /*  [|-x+y>=0; x-y>=0|] */
  x = x + 1; /*  [|-x+y+1>=0; x-y-1>=0|] */
  y = y + 1; /* [|-x+y>=0; x-y>=0|] */
  x = x + 1; /* [|-x+y+1>=0; x-y-1>=0|] */
  y = y + 1; /* [|-x+y>=0; x-y>=0|] */
end

But, ACDL when run with --octagons returns the following meet irreducibles after first deduction stage:
$guard#20
$guard#0
$cond#19

What is the reason for not deducing meet irreducibles similar to Interproc in the first deduction stage ?

**Comment by peterschrammel** [comment]
I get octagonal deductions in https://github.com/diffblue/2ls/commit/565175c41f5d86c42f9e1bbe4f64056f7c1769e3 now. Some regressions fail, though.

**Comment by rajdeep87** [comment]
1> Some octagonal deductions look like this:
!((signed __CPROVER_bitvector[34])-((signed __CPROVER_bitvector[33])y#18) + -((signed __CPROVER_bitvector[34])y#21) >= 0)
What is the interpretation of the first element _signed __CPROVER_bitvector[34]_ ?

2> Just a side note: I ran the regression with interval domain and some of these fails now because deductions are not generated as expected. May be the recent change in the domain for octagon affect interval deductions as well.

**Comment by peterschrammel** [comment]
1. It's a cast.  
2. As suspected earlier, the implementation of split might not be sufficiently robust.
