### ISSUE TITLE
deductions for "lb" variables 

### ISSUE THREAD

**Issue by rajdeep87** [diffblue/2ls#24]
Consider the program below:
int main() { 
  int x=0,i;
  for(i=0;i<=1;i++)  
    x = x+i;
  assert(x>25);
}

The SSA after unwinding=2 is shown below:
!(x#phi21 >= 26 || !$guard#25)
!$guard#ls24%2  
x#17 == 0
$cond#24%2 == TRUE  
$guard#0 == TRUE
$cond#24%1 == TRUE  
i#20 == 0
$guard#25 == ($cond#21 && $guard#21)  
x#phi21 == x#phi21%0  
x#phi21 == ($guard#21%2 && $cond#21%2 ? x#phi21%2 : ($guard#21%1 && $cond#21%1 ? x#phi21%1 : x#phi21%0))
$cond#21 == $cond#21%0  
$guard#21 == $guard#21%0  
$cond#21 == ($guard#21%2 && $cond#21%2 ? $cond#21%2 : ($guard#21%1 && $cond#21%1 ? $cond#21%1 : $cond#21%0))
$guard#21 == ($guard#21%2 && $cond#21%2 ? $guard#21%2 : ($guard#21%1 && $cond#21%1 ? $guard#21%1 : $guard#21%0))
x#22%0 == i#phi21%0 + x#phi21%0  
x#phi21%0 == ($guard#ls24%0 ? x#lb24%0 : x#17) 
x#phi21%0 == x#22%1  
x#22%1 == i#phi21%1 + x#phi21%1  
$guard#22%1 == (!$cond#21%1 && $guard#21%1)  
x#22%2 == i#phi21%2 + x#phi21%2  
$guard#22%2 == (!$cond#21%2 && $guard#21%2)  
x#phi21%1 == x#22%2  
$cond#21%1 == i#phi21%1 >= 2  
$guard#21%1 == ($guard#22%2 && $cond#24%2)
x#phi21%2 == ($guard#ls24%2 ? x#lb24%2 : x#17)  
$cond#21%2 == i#phi21%2 >= 2  
$guard#21%2 == $guard#0
i#phi21 == ($guard#21%2 && $cond#21%2 ? i#phi21%2 : ($guard#21%1 && $cond#21%1 ? i#phi21%1 : i#phi21%0))
$guard#22%0 == (!$cond#21%0 && $guard#21%0) 
$cond#21%0 == i#phi21%0 >= 2  
$guard#21%0 == $guard#0
$guard#21%0 == ($guard#22%1 && $cond#24%1)  
i#23%0 == 1 + i#phi21%0
i#phi21%0 == ($guard#ls24%0 ? i#lb24%0 : i#20)
i#phi21 == i#phi21%0
i#phi21%0 == i#23%1  
i#23%1 == 1 + i#phi21%1  
i#phi21%1 == i#23%2
i#23%2 == 1 + i#phi21%2  
i#phi21%2 == ($guard#ls24%2 ? i#lb24%2 : i#20)                                            

---

 IMPLICATION GRAPH AFTER DEDUCTION PHASE

---

!(i#phi21 >= 3)
!(i#lb24%0 >= 3)
!(-((signed __CPROVER_bitvector[33])i#23%0) >= -2)
!(i#23%0 >= 4)
!(-((signed __CPROVER_bitvector[33])x#phi21) >= 0)
!(x#phi21 >= 2)
!(-((signed __CPROVER_bitvector[33])x#lb24%0) >= 0)
!(x#lb24%0 >= 2)
!(-((signed __CPROVER_bitvector[33])x#22%0) >= -2)
!(x#22%0 >= 4)
!(i#phi21%0 >= 3)
!(-((signed __CPROVER_bitvector[33])x#phi21%0) >= 0)
!(x#phi21%0 >= 2)
!(i#23%1 >= 3)
!(-((signed __CPROVER_bitvector[33])x#22%1) >= 0)
!(x#22%1 >= 2)
$guard#22%2
!(-((signed __CPROVER_bitvector[33])x#phi21%1) >= 1)
!(x#phi21%1 >= 1)
!(i#23%2 >= 2)
!(i#phi21%1 >= 2)
!(x#lb24%0 >= 26)
$guard#21%1
!$cond#21%1
!$cond#21%2
!(-((signed __CPROVER_bitvector[33])x#22%2) >= 1)
!(x#22%2 >= 1)
!(i#phi21%2 >= 1)
!(-((signed __CPROVER_bitvector[33])i#phi21%2) >= 1)
!(i#phi21%2 >= 2147483646)
!(-((signed __CPROVER_bitvector[33])i#23%2) >= 0)
!(i#23%2 >= 2147483647)
!(-((signed __CPROVER_bitvector[33])i#phi21%1) >= 0)
!(i#phi21%1 >= 2147483647)
!(-((signed __CPROVER_bitvector[33])i#23%1) >= -1)
!(-((signed __CPROVER_bitvector[33])i#phi21) >= -1)
!(-((signed __CPROVER_bitvector[33])i#lb24%0) >= -1)
$guard#ls24%0
$guard#22%1
!(-((signed __CPROVER_bitvector[33])i#phi21%0) >= -1)
!$guard#22%0
$guard#21%2
!(-((signed __CPROVER_bitvector[33])x#phi21%2) >= 1)
!(x#phi21%2 >= 1)
!(x#22%1 >= 26)
$guard#21%0
$cond#21%0
!(x#phi21%0 >= 26)
$guard#21
$cond#21
!(-((signed __CPROVER_bitvector[33])i#20) >= 1)
!(i#20 >= 1)
$cond#24%1
$guard#0
$cond#24%2
!(-((signed __CPROVER_bitvector[33])x#17) >= 1)
!(x#17 >= 1)
!$guard#ls24%2
!(x#phi21 >= 26)
$guard#25

---

Completeness check 

---

The value i#lb24%2
 is not complete

The variable i#lb24%2 is expected to be deduced, but it is not deduced -- hence the bug is in deduction. However, the variable i#lb24%0 is correctly deduced. ACDL should return with successful gamma-completeness check in this case.

**Comment by peterschrammel** [comment]
Do you add the ssa's enabling-exprs to the formula? 
I would not expect anything to be deduced for
 i#lb24%2. We currently can only make decisions on it. 
For the completeness check you can ignore *lb* variables. They cannot cause incompleteness if *ls* is false.

**Comment by rajdeep87** [comment]
Currently, all nodes whose enabling_expr does not match get_enabling_exprs() are not added to the worklist. 
What is the effect of adding ssa's enabling_expr to the formula ?
There are two _ls_ variables in above example, _$guard#ls24%0_ and _$guard#ls24%2_
The deduction phase deduce _$guard#ls24%0_  = true and _$guard#ls24%2_ = false
Does the completeness check ignore _lb_ variables only when all the _guard#ls_ are FALSE ?
