### ISSUE TITLE
Support for multiple Propagation strategy

### ISSUE THREAD

**Issue by rajdeep87** [diffblue/2ls#27]
For some real programs (derived from hardware designs), the chaotic iteration strategy seems to be very expensive. In particular, for a program of approx 200 LOC with multiple functions, a large portion of time is spent in the first deduction step (Decision Level 0). We need to implement other 
iteration strategies for comparison:
1> Forward analysis with strongest post-condition -- over approximate analysis
2> Backward analysis with weakest pre-condition -- under approximate analysis

**Comment by peterschrammel** [comment]
1> You should implement Rastrée. To this end,
* subclass the worklist to implement a forward iteration strategy (and right to left propagation)
* subclass the decision heuristics to split on guards (emulate separate analysis of branches, trace partitioning)
* subclass the conflict analysis (is a nop)

2> The propagation phase is over-approximating regardless of the direction. But similar to 1, you can subclass the worklist to implement a backward iteration strategy (and left to right propagation)
