### ISSUE TITLE
Bug in 2ls for assertions outside loop 

### ISSUE THREAD

**Issue by rajdeep87** [diffblue/2ls#29]
Consider a simple program below:
int main() {
  int x=0,i;
  for(i=0;i<=1;i++) {
    x = x+i;
    assert(x<1);
  }
}
When I run 2ls on the above program, it shows VERIFICATION FAILED which is correct !!

Now, I just remove the braces around for loop and put the assertion outside the for loop. 
int main() {
  int x=0,i;
  for(i=0;i<=1;i++)
    x = x+i;
  assert(x<1);
}

On executing the above program, 2ls shows VERIFICATION INCONCLUSIVE.  
Shouldn't it terminate with VERIFICATION FAILED ?

**Comment by peterschrammel** [comment]
No, you need at least one unwinding to find the bug in the second example.

**Comment by rajdeep87** [comment]
Okay.
With --unwind 1, it shows "VERIFICATION INCONCLUSIVE" but with --unwind 2 it shows "VERIFICATION FAILED".

**Comment by peterschrammel** [comment]
Alright then.
