### ISSUE TITLE
Limitation of Forward Iteration Strategy 

### ISSUE THREAD

**Issue by rajdeep87** [diffblue/2ls#31]
The algorithm below for forward iteration strategy over SSA has limitations :
Step 1: Populate worklist with leaves (rhs doesn't have any dependencies)
Step 2: Propagate/deduce right to left (pass lhs variable of the statement to acdl_domain())
Step 3: Add to the worklist the nodes of which all predecessors have been processed.

Now, consider SSA representation for a program: 
N1: !(x#20 == 1u + y#18 || !$guard#20)
N2: $guard#0 == TRUE
N3: $cond#19 == (x#16 == y#18)
N4: x#20 == 1u + x#16
N5: $guard#20 == ($cond#19 && $guard#0)

The leaf nodes are : N2, N3, N4 
When N3 is popped, we cannot deduce any information since deductions in N3 depends on deductions in N5 (cond#19). In other words, the deductions in leaf nodes depends on deductions in non-leaf nodes. So, following Step 3 of above algorithm, the deductions in node N3 that  (x#16 == y#18) is never possible since (cond#19) is not known when N3 is processed and is only known when N5 is processed.

**Comment by rajdeep87** [comment]
I guess this is still not solved. This is a separate issue for the forward iteration strategy only.

**Comment by peterschrammel** [comment]
The forward iteration strategy is a restriction of chaotic iteration. Hence, if the issue is solved for chaotic iteration it must also work for a forward strategy.
