### ISSUE TITLE
Assertions inside for loop

### ISSUE THREAD

**Issue by rajdeep87** [diffblue/2ls#45]
Consider a program below:
int main() {                                                                                   
  int x=0,i;                                                                                   
  for(i=0;i<=6;i++) {                                                                          
    x = x+i;                                                                                   
    assert(x<=10);                                                                             
  }                                                                                            
}   

This leads to conjunction of 8 assertion statements for an unwinding of 7. A conjunction of all 8 assertions are passed to the ACDL solver. The SSA constraints generated for the following two commands are different: 
1> 2ls --verbosity 10 --unwind 7 
2> 2ls --acdl --decision D --propagate P --learning L --unwind 7 

This leads to buggy verification output in ACDL.

**Comment by peterschrammel** [comment]
What is the output?

**Comment by rajdeep87** [comment]
The output of 1) is here:
https://www.cs.ox.ac.uk/people/rajdeep.mukherjee/ssa

The output of 2) is here:
https://www.cs.ox.ac.uk/people/rajdeep.mukherjee/acdl_statement

In particular, there is no variable named x#22 in 1) but there are several instances of this variable in 2)

**Comment by rajdeep87** [comment]
Putting the assertion in the above program outside the for loop yields correct Verification output. 
The bug only occurs when the assertion is inside the loop. If the difference in SSA is not a problem for this, then it could be due to the conjunction of assertions.

**Comment by peterschrammel** [comment]
Run 1) with 2ls --verbosity 10 --unwind 7 --inline. x#6 should become x#22 then.
Your statements in 2) contain the assertion for each unwinding separately. I don't see not(conjunction of assertions) as it should be.

**Comment by rajdeep87** [comment]
The negation of conjunction of assertions is passed to the worklist. So, it is there. See below (marked in bold). 
! (**(!(x#22%0 >= 11) || !$guard#22%0)** && **(!(x#22%1 >= 11) || !$guard#22%1)** && **(!(x#22%2 >= 11) || !$guard#22%2)** && **(!(x#22%3 >= 11) || !$guard#22%3)** && **(!(x#22%4 >= 11) || !$guard#22%4)** && **(!(x#22%5 >= 11) || !$guard#22%5)** && **(!(x#22%6 >= 11) || !$guard#22%6)** && **(!(x#22%7 >= 11) || !$guard#22%7)**)

The problem could due to the following:
In addition to the above conjuncted assertion, we also have individual assertion statements in the worklist which are created as part  of the unrolling of the loop. Do we need to handle these individual assertion statements or we just skip when we pop an individual assertion statement from the worklist during the deduction phase ?
I think we should only handle the above conjuncted assertion and not the individual ones.

**Comment by peterschrammel** [comment]
Of course, the individual assertions must not be there

**Comment by rajdeep87** [comment]
Fixed !! When there are multiple assertions due to unrolling of loop, the algorithm ignores the individual assertions and just takes the negation of conjunction of all assertions. All regression passed successfully.
