### ISSUE TITLE
Error in SSA representation 

### ISSUE THREAD

**Issue by rajdeep87** [diffblue/2ls#50]
Consider the program below:
`{                                                                                  
  int x, y;                                                                            
  _Bool c;                                                                                    
  __CPROVER_assume(1 <= x && x <= 3);                                                         
  if(c)                                                                                       
    x++;                                                                                      
  else                                                                                        
    x--;                                                                                      
  assert(x<0);                                                                                
}`
The SSA representation corresponding to the assignment of x#phi26 is wrong. 

`$cond#21 == (x#16 >= 1 && !(x#16 >= 4))`
`$cond#22 == (c#20 == TRUE)`
`$guard#22 == ($cond#21 && $guard#0)`
`x#23 == 1 + x#16`
`$guard#23 == (!$cond#22 && $guard#22)`
`$cond#24 == TRUE`
`x#25 == -1 + x#16`
`$guard#25 == ($cond#22 && $guard#22)`
 **x#phi26 == ($guard#25 ? x#25 : x#23)** // should this be x#phi26 == ($guard#25 ? x#23 : x#25)
`$guard#26 == ($cond#24 && $guard#23 || $guard#25)`
`!(x#phi26 >= 0) || !$guard#26`

**Comment by peterschrammel** [comment]
It is the line `$cond#22 == (c#20 == TRUE)` that should be `$cond#22 == (c#20 == FALSE)`, which is correct on the master branch. This is already wrong in the goto-program. I am synchronizing with master.

**Comment by peterschrammel** [comment]
Updated. Run the install.sh script to get the right CBMC version after pulling.

**Comment by rajdeep87** [comment]
Yes, pulled your changes and updated CBMC through install.sh
The goto-program is correct as shown below. 
`IF !(c != FALSE) THEN GOTO 1`
  `x = x + 1;`
  `GOTO 2`
  `1: x = x - 1;`
   `2: ASSERT x < 0`

Investigating the conversion from `ID_c_bool` to `bool_typet()` for the variable 'c'

**Comment by rajdeep87** [comment]
Similar example where the boolean conversion introduces error in SSA. This time `c = 0` is concretised to simplify the example.  
`{                                                                                  
  int x, y;                                                                            
  _Bool c = 0;                                                                                    
  __CPROVER_assume(1 <= x && x <= 3);                                                         
  if(c)                                                                                       
    x++;                                                                                      
  else                                                                                        
    x--;                                                                                      
  assert(x<0);                                                                                
}`
The SSA representation is as follows.
`c#21 == FALSE`
`$cond#22 == (x#16 >= 1 && !(x#16 >= 4))`
`$cond#23 == FALSE`
`$guard#23 == ($cond#22 && $guard#0)`
`x#24 == 1 + x#16`
`$guard#24 == (!$cond#23 && $guard#23)`
`$cond#25 == TRUE`
`x#26 == -1 + x#16`
`$guard#26 == ($cond#23 && $guard#23)`
`x#phi27 == ($guard#26 ? x#26 : x#24)`
`$guard#27 == ($cond#25 && $guard#24 || $guard#26)`
`!(x#phi27 >= 0) || !$guard#27`

The goto-function is shown below.
`IF !(c != FALSE) THEN GOTO 1`
`x = x + 1;`
`GOTO 2`
`1: x = x - 1;`

Few observations for the translation to bool_typet(). 
- For the conversion of statement `c = (_Bool)0`, the output is bool_typet(). It first translates the type of the whole expression to bool_typet(), and then translates each lhs and rhs to bool_typet().
This is correct. 
-  The expression that is passed to the replace_c_bool_rec in summarizer/preprocessing_util.cpp is 
` c != FALSE`, but in the goto-program above this is ` !(c != FALSE)`. Should `!(c != FALSE)` be passed to preprocessing_util.cpp instead ? Can this be the reason for SSA error.
